### ISSUE TITLE
Error deserializing user::GetTopAlbums

### ISSUE THREAD

**Issue by vervaekejonathan** [xenzh/lastfm-parse-rs#2]
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Deserialize(Error("invalid type: string \"https://www.last.fm/music/Underworld\", expected a borrowed string", line: 1, column: 82))', src/lastfm/lastfm.rs:42:26

This is the code:

```
        let url = user::GetTopAlbums::request(
            BASE_URL,
            API_KEY,
            None,
            None,
            user,
            Some(Period::OneYear), 
            Some(4), 
            Some(1)            
        ).get_url().unwrap();
    
        let mut data : Vec<u8> = Vec::new();
        get_data::<user::GetTopAlbums>(url, &mut data);
        let top = from_json_slice::<user::GetTopAlbums>(&data);
        println!("{:?}", top.unwrap());
```

**Comment by vervaekejonathan** [comment]
Same for user::GetTopArtists

**Comment by xenzh** [comment]
@vervaekejonathan Please build your code against latest master; your issue should be fixed now.
Didn't expect anyone to use this library, what a surprise!

**Comment by vervaekejonathan** [comment]
@xenzh Thanks! I'm using this to build on my rust skills. It looks like a lot of works was done in this repo, it should be used more!
